source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!

target 'Solitaire-mobile' do
  # TopOn 聚合 SDK
  pod 'TPNiOS', '~> 6.4.50'

  # 广告平台 Adapter：Vungle / Chartboost / Digital Turbine(Fyber) / Bigo
  pod 'TPNVungleSDKAdapter', '~> 6.4.50'
  pod 'TPNChartboostSDKAdapter', '~> 6.4.50'
  pod 'TPNFyberSDKAdapter', '~> 6.4.50'
  pod 'TPNBigoSDKAdapter', '~> 6.4.50'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
      end
    end
  end
end
